# Generated by Django 3.2.4 on 2021-08-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagetotext_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetotext',
            name='caption',
        ),
    ]
